<?php get_header(); ?>
<main class="site-shell">
  <div class="status-line reveal"><div class="signal"><span class="dot"></span><strong>Available for freelance</strong></div><div><?php echo esc_html(date('H:i')); ?> · Worldwide</div></div>
  <section class="control-grid" id="home">
    <article class="tile profile reveal tilt"><div class="tile-inner"><div class="hero-copy"><div class="eyebrow">Creative Developer · UI Builder · Digital Creator</div><h1>ALEX<span>I build modern websites, creative interfaces & digital experiences.</span></h1><p class="muted">A fictional demo portfolio showcasing a modern developer profile, interactive UI, web projects, automation concepts and creative digital products.</p><div class="hero-actions"><a class="pill magnetic" href="#projects">View My Work</a><a class="pill secondary magnetic" href="#contact">Contact Me</a></div></div><div class="portrait-wrap"><img class="portrait" src="<?php echo esc_url(get_template_directory_uri().'/assets/demo-portrait.webp'); ?>" alt="Demo developer portrait"></div></div></article>
    <article class="tile quick reveal tilt" id="services"><div class="tile-inner quick-grid"><a class="quick-btn" href="#projects"><span class="quick-icon active">◉</span><div><strong>Web Development</strong><small>Modern websites & interfaces</small></div></a><a class="quick-btn" href="#projects"><span class="quick-icon">⌁</span><div><strong>UI / UX</strong><small>Design systems & prototypes</small></div></a><a class="quick-btn" href="#projects"><span class="quick-icon">✦</span><div><strong>AI Integration</strong><small>Smart tools & workflows</small></div></a><a class="quick-btn" href="#contact"><span class="quick-icon">↗</span><div><strong>Automation</strong><small>APIs & productivity flows</small></div></a></div></article>
    <article class="tile music reveal tilt"><div class="tile-inner"><div class="now-playing"><img class="cover" src="<?php echo esc_url(get_template_directory_uri().'/assets/demo-portrait.webp'); ?>" alt="cover"><div><div class="eyebrow">Now Playing</div><div class="music-title">Demo Mode</div><div class="muted">Interactive background media</div></div></div><div class="music-controls"><button id="prevBtn" aria-label="Previous">⏮</button><button id="musicBtn" class="play-main" aria-label="Play music">▶</button><button id="nextBtn" aria-label="Next">⏭</button></div><div class="equalizer" id="equalizer"><?php for($i=0;$i<28;$i++) echo '<i></i>'; ?></div></div></article>
    <article class="tile slider-tile reveal tilt"><span class="slider-label">Brightness <b id="brightnessValue">100%</b></span><div class="vertical-control interactive-control brightness-control"><div class="vertical-fill" id="brightnessFill"></div><input id="brightnessSlider" class="vertical-range" type="range" min="35" max="130" value="100" aria-label="Website brightness"><span class="vertical-icon">☀</span></div></article>
    <article class="tile slider-tile reveal tilt vol"><span class="slider-label">Volume <b id="volumeValue">70%</b></span><div class="vertical-control interactive-control volume-control"><div class="vertical-fill" id="volumeFill"></div><input id="volumeSlider" class="vertical-range" type="range" min="0" max="100" value="70" aria-label="Music volume"><span class="vertical-icon" id="volumeIcon">🔊</span></div></article>
    <article class="tile focus reveal tilt"><div class="tile-inner"><div class="moon">☾</div><div><div class="eyebrow">Focus</div><h3>Build Mode</h3><p class="muted">Concept → design → code → launch.</p></div></div></article>
    <div class="round-actions reveal"><a class="round-action" href="#projects"><span class="round-icon">⚡</span><b>Frontend</b></a><a class="round-action" href="#projects"><span class="round-icon">⌘</span><b>Design</b></a><a class="round-action" href="#projects"><span class="round-icon">◌</span><b>AI Tools</b></a><a class="round-action" href="#contact"><span class="round-icon">✉</span><b>Contact</b></a></div>
    <article class="tile projects reveal tilt" id="projects"><div class="tile-inner"><div class="eyebrow">Selected Work</div><h2>Demo Projects</h2><div class="projects-grid"><div class="project-card"><span class="tag">Web</span><div><h3>Nova Studio</h3><p class="muted">A polished creative agency landing page with motion, responsive layouts and conversion-focused sections.</p></div></div><div class="project-card"><span class="tag">Dashboard</span><div><h3>TaskFlow</h3><p class="muted">A fictional productivity dashboard with team activity, analytics, filters and workflow controls.</p></div></div><div class="project-card"><span class="tag">AI</span><div><h3>Prompt Studio</h3><p class="muted">A sample AI interface for drafting, improving and organizing prompts inside a clean workspace.</p></div></div><div class="project-card"><span class="tag">Commerce</span><div><h3>North Shop</h3><p class="muted">A demo storefront concept with product discovery, cart interactions and modern checkout UI.</p></div></div></div></div></article>
    <article class="tile contact reveal tilt" id="contact"><div class="tile-inner"><div class="eyebrow">Start a project</div><h2>Let’s build.</h2><p class="muted">This is demo content for a portfolio theme. Replace these placeholders with your own bio, services, projects and contact information.</p><div class="contact-links"><a class="contact-link" href="mailto:hello@example.com"><span>Email · hello@example.com</span><strong>↗</strong></a><a class="contact-link" href="https://discord.com/" target="_blank" rel="noopener"><span>Discord</span><strong>↗</strong></a><a class="contact-link" href="https://github.com/example" target="_blank" rel="noopener"><span>GitHub</span><strong>↗</strong></a></div></div></article>
  </section>
  <footer class="footer"><span>© <?php echo esc_html(date('Y')); ?> Alex — Demo Portfolio.</span><span>Design · Code · Create</span></footer>
</main><div class="floating-note"><span>♫</span><span id="musicState">Music muted</span></div><div class="cursor-dot"></div><div class="cursor-ring"></div><?php get_footer(); ?>